### SIGNUP
POST http://localhost:3333/signup
Content-Type: application/json

{
  "name": "Eric Cartman",
  "email": "juan@gmail.com",
  "password": "hi"
  
}

### LOGIN
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "juan@gmail.com",
  "password": "juan.dev"
}

### SECURE ROUTE
GET http://localhost:3333/secure-route
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjE2LCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWF0IjoxNzYzMTUyNTkxLCJleHAiOjE3NjMxNTYxOTF9.VNj4Wg4ZSDraRdKDI1AY09SkZwpKGze04PgGOaM5s8k

### PROFILE
GET http://localhost:3333/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjIxLCJ1c2VybmFtZSI6Ikp1YW4gT2xpdmVpcmEiLCJpYXQiOjE3NzEzNDA1ODcsImV4cCI6MTc3MTM0NDE4N30.gcRzSs4NMssOK72At_sgLq8McPLAd76lZWvcazZQnbQ

### ORDERS
GET http://localhost:3333/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjIxLCJ1c2VybmFtZSI6Ikp1YW4gT2xpdmVpcmEiLCJpYXQiOjE3NzEzNDExMTIsImV4cCI6MTgwNzM0MTExMn0.fTIiK4be9bfWbxnXk01E_KzWwnWHlFuFU3GAmDb8QWA  

### PRODUCTS
GET http://localhost:3333/products/eletronics?page_number=2&page_size=3&page_sort=price

###
GET http://localhost:3333/products?page_number=3&page_size=3

### CHECKOUT
POST http://localhost:3333/checkout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjIxLCJ1c2VybmFtZSI6Ikp1YW4gT2xpdmVpcmEiLCJpYXQiOjE3NzEzNDExMTIsImV4cCI6MTgwNzM0MTExMn0.fTIiK4be9bfWbxnXk01E_KzWwnWHlFuFU3GAmDb8QWA

[
  {
    "id": 2,
    "name": "Samsung Galaxy S24",
    "quantity": 1,
    "desc": "max 75",
    "price": "899.99"
  },
  {
    "id": 3,
    "name": "MacBook Pro 16\"",
    "quantity": 1,
    "desc": "max 30",
    "price": "2499.99"
  }

]

## Juan Oliveira email: juan@gmail.com password: juan.dev Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjE4LCJ1c2VybmFtZSI6Ikp1YW4gT2xpdmVpcmEiLCJpYXQiOjE3NjMyNDM5NzksImV4cCI6MTc2MzI0NzU3OX0.x7r_pzfWyHez02gBKK8yqlFpc4yMl9bHtWmIR3wzrsE
## username Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjE2LCJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWF0IjoxNzYzMjQ0NDUzLCJleHAiOjE3NjMyNDgwNTN9.AtRNdkuluRWWeAlOl-MWesBeC_WrxPDDJJJlQx06KvA