import db from "./config/db.js"

//db('product_category').select('*').then(res => { console.log(res) })
//db('product_category').insert({ category_name: 'Processors (CPU)', slug: 'processors', parent_category_id: 3 }).then(res => {console.log(res)})
//db('product').insert({ product_name: '', sku: '' })
//await db.transaction(async (trx) => {
  await trx('product').insert([
    {
      product_name: 'Intel Core i9-14900K',
      sku: 'CPU-14900K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 599.99,
      compare_at_price: 649.99,
      product_desc: '14th Gen flagship Intel CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i7-14700K',
      sku: 'CPU-14700K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 419.99,
      compare_at_price: 459.99,
      product_desc: 'High performance Intel CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i5-14600K',
      sku: 'CPU-14600K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 319.99,
      compare_at_price: 349.99,
      product_desc: 'Mid-range Intel CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i9-13900K',
      sku: 'CPU-13900K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 549.99,
      compare_at_price: 599.99,
      product_desc: '13th Gen high-end CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i7-13700K',
      sku: 'CPU-13700K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 379.99,
      compare_at_price: 419.99,
      product_desc: 'Balanced Intel CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i5-13600K',
      sku: 'CPU-13600K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 289.99,
      compare_at_price: 319.99,
      product_desc: 'Best value Intel CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 9 7950X',
      sku: 'CPU-7950X',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 699.99,
      compare_at_price: 749.99,
      product_desc: 'Top-tier AMD CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 9 7900X',
      sku: 'CPU-7900X',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 549.99,
      compare_at_price: 599.99,
      product_desc: 'High-end AMD CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 7 7800X3D',
      sku: 'CPU-7800X3D',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 449.99,
      compare_at_price: 499.99,
      product_desc: 'Gaming optimized CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 7 7700X',
      sku: 'CPU-7700X',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 399.99,
      compare_at_price: 429.99,
      product_desc: 'Strong gaming CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 5 7600X',
      sku: 'CPU-7600X',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 299.99,
      compare_at_price: 329.99,
      product_desc: 'Entry enthusiast CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 5 5600X',
      sku: 'CPU-5600X',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 199.99,
      compare_at_price: 229.99,
      product_desc: 'Popular budget CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 7 5800X',
      sku: 'CPU-5800X',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 299.99,
      compare_at_price: 349.99,
      product_desc: 'Previous gen high-end CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 9 5900X',
      sku: 'CPU-5900X',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 349.99,
      compare_at_price: 399.99,
      product_desc: '12-core AMD CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i5-12600K',
      sku: 'CPU-12600K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 259.99,
      compare_at_price: 299.99,
      product_desc: '12th Gen strong CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i7-12700K',
      sku: 'CPU-12700K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 349.99,
      compare_at_price: 399.99,
      product_desc: 'Balanced 12th Gen CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i9-12900K',
      sku: 'CPU-12900K',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 449.99,
      compare_at_price: 499.99,
      product_desc: '12th Gen flagship',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 5 5500',
      sku: 'CPU-5500',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 129.99,
      compare_at_price: 149.99,
      product_desc: 'Budget AMD CPU',
      is_active: true
    },
    {
      product_name: 'Intel Core i3-13100',
      sku: 'CPU-13100',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 149.99,
      compare_at_price: 169.99,
      product_desc: 'Entry-level Intel CPU',
      is_active: true
    },
    {
      product_name: 'AMD Ryzen 3 4100',
      sku: 'CPU-4100',
      dimension_weight: 0.2,
      dimension_height: 4,
      dimension_width: 4,
      dimension_depth: 0.5,
      dimension_unit: 'cm',
      weight_unit: 'kg',
      price: 99.99,
      compare_at_price: 119.99,
      product_desc: 'Low-cost AMD CPU',
      is_active: true
    }
  ]);
//});